const PRE = 'N';
export default {
    tooltip: PRE + 'Tooltip',
    popover: PRE + 'Popover',
    button: PRE + 'Button',
    slider: PRE + 'Slider',
    rate: PRE + 'Rate',
    upload: 'fcUpload',
    cascader: PRE + 'Cascader',
    timePicker: PRE + 'TimePicker',
    datePicker: PRE + 'DatePicker',
    'switch': PRE + 'Switch',
    select: PRE + 'Select',
    checkbox: 'fc-checkbox',
    radio: 'fc-radio',
    inputNumber: PRE + 'InputNumber',
    dynamicTags: PRE + 'DynamicTags',
    tag: PRE + 'DynamicTag',
    colorPicker: PRE + 'ColorPicker',
    search: PRE + 'InputSearch',
    input: PRE + 'Input',
    textarea: PRE + 'Input',
    password: PRE + 'InputPassword',
    formItem: PRE + 'FormItem',
    form: PRE + 'Form',
    frame: 'fcFrame',
    col: PRE + 'Col',
    row: PRE + 'Row',
    tree: PRE + 'Tree',
    treeSelect: PRE + 'TreeSelect',
    autoComplete: PRE + 'AutoComplete',
    transfer: PRE + 'Transfer',
    mention: PRE + 'Mention',
    inputOtp: PRE + 'InputOtp',
    dynamicInput: PRE + 'DynamicInput',
    group: 'fcGroup',
    array: 'fcGroup',
    subForm: 'fcSubForm',
    object: 'fcSubForm',
}
