const PRE = 't';
export default {
    button: PRE + 'Button',
    icon: PRE + 'Icon',
    slider: PRE + 'Slider',
    upload: 'fcUpload',
    cascader: PRE + 'Cascader',
    popup: PRE + 'Popup',
    tooltip: PRE + 'Tooltip',
    colorPicker: PRE + 'ColorPicker',
    dateRangePicker: PRE + 'DateRangePicker',
    datePicker: PRE + 'DatePicker',
    timePicker: PRE + 'TimePicker',
    timeRangePicker: PRE + 'TimeRangePicker',
    'switch': PRE + 'Switch',
    select: PRE + 'Select',
    checkbox: PRE + 'CheckboxGroup',
    radio: PRE + 'RadioGroup',
    inputNumber: PRE + 'InputNumber',
    number: PRE + 'InputNumber',
    input: PRE + 'Input',
    rangeInput: PRE + 'RangeInput',
    tagInput: PRE + 'TagInput',
    textarea: PRE + 'Textarea',
    formItem: PRE + 'FormItem',
    form: PRE + 'Form',
    frame: 'fcFrame',
    col: PRE + 'Col',
    row: PRE + 'Row',
    treeSelect: PRE + 'TreeSelect',
    transfer: PRE + 'Transfer',
    tree: PRE + 'Tree',
    group: 'fcGroup',
    object: 'fcSubForm',
    subForm: 'fcSubForm',
}
