const PRE = 'tiny-';
export default {
    button: PRE + 'button',
    icon: PRE + 'svg-icon',
    layout: PRE + 'layout',
    slider: PRE + 'slider',
    rate: PRE + 'rate',
    cascader: PRE + 'cascader',
    popover: PRE + 'popover',
    tooltip: PRE + 'tooltip',
    colorPicker: PRE + 'color-picker',
    timePicker: PRE + 'time-picker',
    timeSelect: PRE + 'time-select',
    datePicker: PRE + 'date-picker',
    'switch': PRE + 'switch',
    inputNumber: PRE + 'numeric',
    numeric: PRE + 'numeric',
    input: PRE + 'input',
    textarea: PRE + 'input',
    formItem: PRE + 'form-item',
    form: PRE + 'form',
    col: PRE + 'col',
    row: PRE + 'row',
    autoComplete: PRE + 'autocomplete',
    auto: PRE + 'autocomplete',
    treeSelect: PRE + 'tree-select',
    ipAddress: PRE + 'ip-address',
    search: PRE + 'search',
    transfer: PRE + 'transfer',
    select: PRE + 'select',
    checkbox: PRE + 'checkbox-group',
    radio: PRE + 'radio-group',
    tree: PRE + 'tree',
    upload: 'fc-upload',
    frame: 'fc-frame',
    group: 'fc-group',
    array: 'fc-group',
    object: 'fc-sub-form',
    subForm: 'fc-sub-form',
};
