const PRE = 'van';
export default {
    button: PRE + '-button',
    icon: PRE + '-icon',
    slider: PRE + '-slider',
    stepper: PRE + '-stepper',
    rate: PRE + '-rate',
    uploader: 'fc-uploader',
    cell: PRE + '-cell',
    timePicker: 'fc-time-picker',
    datePicker: 'fc-date-picker',
    'switch': PRE + '-switch',
    select: 'fc-select',
    cascader: 'fc-cascader',
    calendar: 'fc-calendar',
    checkbox: 'fc-checkbox',
    radio: 'fc-radio',
    input: PRE + '-field',
    field: PRE + '-field',
    formItem: PRE + '-field',
    form: PRE + '-form',
    col: PRE + '-col',
    row: PRE + '-row',
    group: 'fc-group',
    object: 'fc-sub-form',
    subForm: 'fc-sub-form',
}
