export default {
    button: 'a-button',
    icon: 'a-icon',
    slider: 'a-slider',
    rate: 'a-rate',
    upload: 'fc-upload',
    cascader: 'a-cascader',
    timePicker: 'a-time-picker',
    datePicker: 'a-date-picker',
    rangePicker: 'a-range-picker',
    weekPicker: 'a-week-picker',
    monthPicker: 'a-month-picker',
    'switch': 'a-switch',
    select: 'a-select',
    checkbox: 'a-checkbox-group',
    radio: 'a-radio-group',
    inputNumber: 'a-input-number',
    search: 'a-input-search',
    textarea: 'a-textarea',
    formItem: 'a-form-model-item',
    form: 'a-form-model',
    frame: 'fc-frame',
    col: 'a-col',
    row: 'a-row',
    tree: 'a-tree',
    autoComplete: 'a-auto-complete',
    group: 'fc-group',
}
