export default {
    button: 'elButton',
    icon: 'i',
    slider: 'elSlider',
    rate: 'elRate',
    upload: 'fcUpload',
    cascader: 'elCascader',
    colorPicker: 'elColorPicker',
    timePicker: 'elTimePicker',
    datePicker: 'elDatePicker',
    'switch': 'elSwitch',
    select: 'fcSelect',
    checkbox: 'fcCheckbox',
    radio: 'fcRadio',
    inputNumber: 'elInputNumber',
    input: 'elInput',
    formItem: 'elFormItem',
    form: 'elForm',
    frame: 'fcFrame',
    col: 'elCol',
    row: 'elRow',
    tree: 'fcTree',
    autoComplete: 'elAutocomplete',
    group: 'fcGroup',
}
