export default {
    modal: 'el-dialog',
    progress: 'el-progress',
    button: 'el-button',
    icon: 'i',
    slider: 'el-slider',
    rate: 'el-rate',
    upload: 'el-upload',
    cascader: 'el-cascader',
    colorPicker: 'el-color-picker',
    timePicker: 'el-time-picker',
    datePicker: 'el-date-picker',
    'switch': 'el-switch',
    option: 'el-option',
    select: 'el-select',
    checkbox: 'fc-elm-checkbox',
    radio: 'el-radio',
    radioGroup: 'el-radio-group',
    radioBtn: 'el-radio-button',
    inputNumber: 'el-input-number',
    input: 'el-input',
    formItem: 'el-form-Item',
    form: 'el-form',
    col: 'el-col',
    row: 'el-row',
    tree: 'el-tree',
    autoComplete: 'el-autocomplete',
}