const PRE = 'a';
export default {
    tooltip: PRE + 'Tooltip',
    popover: PRE + 'Popover',
    button: PRE + 'Button',
    slider: PRE + 'Slider',
    rate: PRE + 'Rate',
    upload: 'fcUpload',
    cascader: PRE + 'Cascader',
    timePicker: PRE + 'TimePicker',
    timeRangePicker: PRE + 'TimeRangePicker',
    datePicker: PRE + 'DatePicker',
    rangePicker: PRE + 'RangePicker',
    'switch': PRE + 'Switch',
    select: PRE + 'Select',
    checkbox: 'fc-checkbox',
    radio: 'fc-radio',
    inputNumber: PRE + 'InputNumber',
    search: PRE + 'InputSearch',
    inputTag: PRE + 'InputTag',
    textarea: PRE + 'Textarea',
    password: PRE + 'InputPassword',
    formItem: PRE + 'FormItem',
    form: PRE + 'Form',
    frame: 'fcFrame',
    col: PRE + 'Col',
    row: PRE + 'Row',
    tree: PRE + 'Tree',
    autoComplete: PRE + 'AutoComplete',
    group: 'fcGroup',
    subForm: 'fcSubForm',
    object: 'fcSubForm',
}
